    units        metal
    atom_style   full      # <- Requires each atom has a MolID and Charge.
                           #    This is not necessary.  (Why use "full"?
                           #    The "full" atom style is useful if you want to
                           #    mix the aluminum with other molecules later.
                           #    Otherwise, just use "atom_style atomic", and
                           #    and remove the 2nd and 4th columns above.)
    pair_style	 eam/alloy
